#!/bin/sh
flatpak install --system --bundle  /usr/share/deepin-flatpak/app/com.deepin.ScreenShot/x86_64/master/bundle
rm /usr/share/deepin-flatpak/app/com.deepin.ScreenShot/x86_64/master/bundle
flatpak run --command=fc-cache com.deepin.ScreenShot
for f in `ls -d /home/*/`;
	do
		mkdir -p $f/.var/app/com.deepin.ScreenShot/cache/;
		USER=`echo $f|cut -d '/' -f 3`;
		cp -rf /root/.var/app/com.deepin.Screenshot/cache/fontconfig/ $f.var/app/com.deepin.ScreenShot/cache/
		chown -R $USER:$USER $f
done

exit 0
