#!/bin/sh
flatpak install --system --bundle  /usr/share/deepin-flatpak/app/com.deepin.ScreenShot/x86_64/master/bundle
rm /usr/share/deepin-flatpak/app/com.deepin.ScreenShot/x86_64/master/bundle
set -e
for f in `ls -d /home/*/`;
	do
		mkdir -p $f/.var/app/com.deepin.Music/cache/
		tar -zxvf /usr/share/deepin-flatpak/runtime/com.deepin.Platform/x86_64/15.5/fontconfig.tar.gz -C $f/.var/app/com.deepin.Music/cache/
done

exit 0
